"""Initial Migration

Revision ID: 941258031d37
Revises: 
Create Date: 2021-04-29 09:52:47.872661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941258031d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_point', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('depart_time', sa.DateTime(), nullable=False),
    sa.Column('et_arrival', sa.DateTime(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seats_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sqlite_sequence')
    op.drop_table('requests')
    op.drop_table('rides')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(length=120), nullable=False),
    sa.Column('email', sa.TEXT(length=120), nullable=False),
    sa.Column('password', sa.TEXT(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('starting_point', sa.TEXT(length=256), nullable=False),
    sa.Column('destination', sa.TEXT(length=256), nullable=False),
    sa.Column('depart_time', sa.TEXT(length=256), nullable=False),
    sa.Column('eta', sa.TEXT(length=256), nullable=False),
    sa.Column('seats', sa.INTEGER(), nullable=False),
    sa.Column('vehicle', sa.TEXT(length=120), nullable=False),
    sa.Column('driver', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['driver'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ride_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('destination', sa.TEXT(length=256), nullable=False),
    sa.Column('req_status', sa.TEXT(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('interest')
    op.drop_table('ride')
    op.drop_table('user')
    # ### end Alembic commands ###
